### ISSUE TITLE
Referenced external .JS resource not found

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/hierplane#45]
See https://github.com/allenai/hierplane/blob/master/README.md

In its current iteration, https://unpkg.com/hierplane/dist/static/hierplane.min.js does not exist, however https://unpkg.com/hierplane/dist/static/hierplane.bundle.js does.

**Comment by aaronsarnat** [comment]
@codeviking ran into this while working on embedding a tree on the hierplane homepage. I suggest we either generate and host a minified version (seems the most logical) or at the very least update the README to point to the `...bundle.js` resource that does exist.

**Comment by codeviking** [comment]
Weird! It's supposed to exist.  I can fix this on Monday.
