### ISSUE TITLE
Add a `removeTree` method

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/hierplane#47]
Would be nice to have a built-in way to destroy a tree if need be.

**Comment by codeviking** [comment]
@aaronsarnat Can you be more specific about the use case here?

Are you effectively asking for something like this:

```
const renderedTree = hierplane.renderTree(...);
renderedTree.remove();
```

The way we do it in our dev fixture is via good ole' vanillaJS:

```
container.removeChild(container.firstElementChild);
```

Where `container` is the containing element, and `firstElementChild` is the rendered tree.

We could definitely implement this, that said I'd expect most web developers to be familiar with the DOM APIs that allow for this.

Thoughts?
