### ISSUE TITLE
Consider moving Hierplane website to separate repo

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/hierplane#73]

**Comment by codeviking** [comment]
We should not do this, the overhead of an extra repository for a single-page, simple site isn't worth it.  I realize there's some friction locally when switching branches, but you should just craft aliases / local tooling that makes it easy / resolves those difficulties.

The intent and utility of the magic `gh-pages` branch is such that you can attach a website about a project to it's source code.  That way as a project changes, it's easy to keep the website in sync, as it's something that lives alongside the source artifact.
