### ISSUE TITLE
Compatibility Issues With New Version Of React

### ISSUE THREAD

**Issue by GillesFerone** [allenai/hierplane#88]
Greetings,
First of all, thank you for this great parsed tree visualization.
Unfortunately, I haven't been able to implement it in my ReactJS application.
I followed the following steps:

1. Successfully installed the NPM package.
`npm install --save hierplane`

2. Then imported the tree in my .js file.
`import { Tree } from 'hierplane';`

Got the following error message:
```
bundle.js:17434 Uncaught TypeError: Cannot read property 'string' of undefined
    at Object.<anonymous> (bundle.js:17434)
    at __webpack_require__ (bundle.js:20)
    at Object.defineProperty.value (bundle.js:65924)
    at __webpack_require__ (bundle.js:20)
    at Object.defineProperty.value (bundle.js:66170)
    at __webpack_require__ (bundle.js:20)
    at Object.defineProperty.value (bundle.js:67139)
    at __webpack_require__ (bundle.js:20)
    at Object.defineProperty.value (bundle.js:67783)
    at __webpack_require__ (bundle.js:20)
```

Which points to the second line of code in this snippet:
```
Icon.propTypes = {
  wrapperClass: _react.PropTypes.string,
  symbol: _react.PropTypes.string
};
```

My version of React (**16.3.2**) does not contain PropTypes. 
Which is in line with the fact that PropTypes has been removed from React starting at version v15.5.
Looking at the source code I can see that **`react.PropTypes`** is being referenced across most classes.

Is there a way I can work around this issue with the existing package (Without messing with my React version)?
Is there any plan for making this package compatible with the newest version of React?

Thank you.

**Comment by codeviking** [comment]
Hi @GillesFerone. Apologies for the late reply, but this should be resolved with the latest version (`0.2.0`).  We've added support for React 16.

Let me know if that's not the case (and feel free to re-open the issue).
